/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20Minimal } from "./IERC20Minimal";
export * as factories from "./factories";
export { IERC20Minimal__factory } from "./factories/IERC20Minimal__factory";
